### ISSUE TITLE
Add "sibling"  (or "sibling-*") action(s)

### ISSUE THREAD

**Issue by yarikoptic** [vsoch/datalad-action#14]
Came up in a chat with @asmacdo thinking about being able to ease establishing github action which would do something (like fetch logs, run con/tinuous, etc), add content into git-annex, and share it through some new or established remote.   And it should work for some (free) typically available to mortals types of git-annex special remotes: dropbox, box.com, ...  So, seems like anything what `rclone` supports?

In principle all that could be done via some collection of steps such as 
- install needed tools (e.g., rclone, git-annex-remote-rclone)
- possibly do needed configuration for the tool (e.g. rclone)
- do needed `create-sibling-*` if done first time or just enabling that known sibling

and all of that would be done from some lean configuration like

```yaml
      - name: Download Dataset
        uses: datalad/datalad-action/sibling@main
        with:
          remote-type: dropbox
          remote-prefix: thisrepo-annex/  # custom to that type of remote option
          dataset: .  # optional,
          remote-name: dropbox # optional, match the type by default
          password: ${{ secrets.REMOTE_PASSWORD }}
```

where for `remote-type` "dropbox" action does needed installation, and configuration as needed given the parameters

Note that `datalad-installer` already supports installation of rclone and git-annex-remote-rclone.  So it could be installed/used to install rclone and special remote.

The point is that we would ensure that there is a desired sibling and that content could be `datalad push`ed to it.  We could even take further and add `/push` action to make it fully "from spec" and not require custom `datalad` invocations.

may be we need first to formalize some thin layer of helpers in `datalad-rclone` extension?
